default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wordplay_development

test:
  <<: *default
  database: wordplay_test

production:
  <<: *default
  database: wordplay_production
  username: wordplay
  password: <%= ENV['WORDPLAY_DATABASE_PASSWORD'] %>
